/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

import java.awt.Color;

/**
 *
 * @author LENOVO-PC
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlpelanggan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlpengambilan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlpaket = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlpenerimaan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlexit = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnllogout = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnllaporan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        pnlpelanggan.setBackground(new java.awt.Color(153, 0, 153));
        pnlpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlpelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlpelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlpelangganMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 0, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User-Profile-70.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pelanggan");

        javax.swing.GroupLayout pnlpelangganLayout = new javax.swing.GroupLayout(pnlpelanggan);
        pnlpelanggan.setLayout(pnlpelangganLayout);
        pnlpelangganLayout.setHorizontalGroup(
            pnlpelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpelangganLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlpelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlpelangganLayout.setVerticalGroup(
            pnlpelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpelangganLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlpengambilan.setBackground(new java.awt.Color(255, 102, 0));
        pnlpengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlpengambilanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlpengambilanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlpengambilanMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaction.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pengambilan &");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pembayaran");

        javax.swing.GroupLayout pnlpengambilanLayout = new javax.swing.GroupLayout(pnlpengambilan);
        pnlpengambilan.setLayout(pnlpengambilanLayout);
        pnlpengambilanLayout.setHorizontalGroup(
            pnlpengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpengambilanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlpengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        pnlpengambilanLayout.setVerticalGroup(
            pnlpengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpengambilanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlpengambilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pnlpengambilanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlpaket.setBackground(new java.awt.Color(102, 204, 0));
        pnlpaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlpaketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlpaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlpaketMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 0, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Data-Add-70.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Paket");

        javax.swing.GroupLayout pnlpaketLayout = new javax.swing.GroupLayout(pnlpaket);
        pnlpaket.setLayout(pnlpaketLayout);
        pnlpaketLayout.setHorizontalGroup(
            pnlpaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpaketLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlpaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpaketLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlpaketLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))))
        );
        pnlpaketLayout.setVerticalGroup(
            pnlpaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpaketLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlpenerimaan.setBackground(new java.awt.Color(255, 0, 0));
        pnlpenerimaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlpenerimaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlpenerimaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlpenerimaanMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(102, 0, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Load-Man-70.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Penerimaan");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cucian");

        javax.swing.GroupLayout pnlpenerimaanLayout = new javax.swing.GroupLayout(pnlpenerimaan);
        pnlpenerimaan.setLayout(pnlpenerimaanLayout);
        pnlpenerimaanLayout.setHorizontalGroup(
            pnlpenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpenerimaanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlpenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpenerimaanLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(pnlpenerimaanLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlpenerimaanLayout.setVerticalGroup(
            pnlpenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpenerimaanLayout.createSequentialGroup()
                .addGroup(pnlpenerimaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpenerimaanLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(pnlpenerimaanLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnlexit.setBackground(new java.awt.Color(0, 0, 204));
        pnlexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlexitMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(102, 0, 153));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Exit");

        javax.swing.GroupLayout pnlexitLayout = new javax.swing.GroupLayout(pnlexit);
        pnlexit.setLayout(pnlexitLayout);
        pnlexitLayout.setHorizontalGroup(
            pnlexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlexitLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlexitLayout.setVerticalGroup(
            pnlexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlexitLayout.createSequentialGroup()
                .addGroup(pnlexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlexitLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13))
                    .addGroup(pnlexitLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnllogout.setBackground(new java.awt.Color(255, 0, 204));
        pnllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnllogoutMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(102, 0, 153));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Logout");

        javax.swing.GroupLayout pnllogoutLayout = new javax.swing.GroupLayout(pnllogout);
        pnllogout.setLayout(pnllogoutLayout);
        pnllogoutLayout.setHorizontalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllogoutLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(24, 24, 24))
        );
        pnllogoutLayout.setVerticalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllogoutLayout.createSequentialGroup()
                .addGroup(pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnllogoutLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14))
                    .addGroup(pnllogoutLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnllaporan.setBackground(new java.awt.Color(255, 204, 0));
        pnllaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnllaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnllaporanMouseExited(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(102, 0, 153));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Printer-70.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Laporan");

        javax.swing.GroupLayout pnllaporanLayout = new javax.swing.GroupLayout(pnllaporan);
        pnllaporan.setLayout(pnllaporanLayout);
        pnllaporanLayout.setHorizontalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllaporanLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(22, 22, 22))
        );
        pnllaporanLayout.setVerticalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllaporanLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllaporanLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllaporanLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnllaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlpengambilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlpenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlpelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnllogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlpenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlpaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnllaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlpengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpelangganMouseClicked
        // TODO add your handling code here:
        FormPelanggan n = new FormPelanggan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_pnlpelangganMouseClicked

    private void pnlexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlexitMouseClicked

    private void pnllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseClicked
        // TODO add your handling code here:
        login n = new login(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_pnllogoutMouseClicked

    private void pnlpengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpengambilanMouseClicked
        // TODO add your handling code here:
        FormPengambilan n = new FormPengambilan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_pnlpengambilanMouseClicked

    private void pnlpaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpaketMouseClicked
        // TODO add your handling code here:
        FormPaket n = new FormPaket(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_pnlpaketMouseClicked

    private void pnlpenerimaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpenerimaanMouseClicked
        // TODO add your handling code here:
        FormPenerimaan n = new FormPenerimaan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_pnlpenerimaanMouseClicked

    private void pnllaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllaporanMouseClicked
        // TODO add your handling code here:
        FormLaporan n = new FormLaporan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_pnllaporanMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        login n = new login(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        FormPenerimaan n = new FormPenerimaan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        FormPengambilan n = new FormPengambilan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        FormPelanggan n = new FormPelanggan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        FormPaket n = new FormPaket(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        FormLaporan n = new FormLaporan(); 
                    n.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void pnlexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlexitMouseEntered
        // TODO add your handling code here:
        pnlexit.setBackground(Color.decode("#3333FF")); 
    }//GEN-LAST:event_pnlexitMouseEntered

    private void pnlexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlexitMouseExited
        // TODO add your handling code here:
        pnlexit.setBackground(Color.decode("#0000CC")); 
    }//GEN-LAST:event_pnlexitMouseExited

    private void pnllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseEntered
        // TODO add your handling code here:
        pnllogout.setBackground(Color.decode("#FF66CC"));
    }//GEN-LAST:event_pnllogoutMouseEntered

    private void pnllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseExited
        // TODO add your handling code here:
        pnllogout.setBackground(Color.decode("#FF00CC"));
    }//GEN-LAST:event_pnllogoutMouseExited

    private void pnlpenerimaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpenerimaanMouseEntered
        // TODO add your handling code here:
        pnlpenerimaan.setBackground(Color.decode("#FF6666"));
    }//GEN-LAST:event_pnlpenerimaanMouseEntered

    private void pnlpenerimaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpenerimaanMouseExited
        // TODO add your handling code here:
        pnlpenerimaan.setBackground(Color.decode("#FF0000"));
    }//GEN-LAST:event_pnlpenerimaanMouseExited

    private void pnlpengambilanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpengambilanMouseEntered
        // TODO add your handling code here:
        pnlpengambilan.setBackground(Color.decode("#FF9966"));
    }//GEN-LAST:event_pnlpengambilanMouseEntered

    private void pnlpengambilanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpengambilanMouseExited
        // TODO add your handling code here:
        pnlpengambilan.setBackground(Color.decode("#FF6600"));
    }//GEN-LAST:event_pnlpengambilanMouseExited

    private void pnlpaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpaketMouseEntered
        // TODO add your handling code here:
        pnlpaket.setBackground(Color.decode("#66FF66"));
    }//GEN-LAST:event_pnlpaketMouseEntered

    private void pnlpaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpaketMouseExited
        // TODO add your handling code here:
        pnlpaket.setBackground(Color.decode("#66CC00"));
    }//GEN-LAST:event_pnlpaketMouseExited

    private void pnlpelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpelangganMouseEntered
        // TODO add your handling code here:
        pnlpelanggan.setBackground(Color.decode("#CC00FF"));
    }//GEN-LAST:event_pnlpelangganMouseEntered

    private void pnlpelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlpelangganMouseExited
        // TODO add your handling code here:
        pnlpelanggan.setBackground(Color.decode("#990099"));
    }//GEN-LAST:event_pnlpelangganMouseExited

    private void pnllaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllaporanMouseEntered
        // TODO add your handling code here:
        pnllaporan.setBackground(Color.decode("#FFFF66"));
    }//GEN-LAST:event_pnllaporanMouseEntered

    private void pnllaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllaporanMouseExited
        // TODO add your handling code here:
        pnllaporan.setBackground(Color.decode("#FFCC00"));
    }//GEN-LAST:event_pnllaporanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlexit;
    private javax.swing.JPanel pnllaporan;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlpaket;
    private javax.swing.JPanel pnlpelanggan;
    private javax.swing.JPanel pnlpenerimaan;
    private javax.swing.JPanel pnlpengambilan;
    // End of variables declaration//GEN-END:variables
}
